apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bluebubbles-chatgpt-agent
resources:
- be-components.yaml
images:
- name: ghcr.io/omega-bred/bluebubbles-chatgpt-agent
  newName: ghcr.io/omega-bred/bluebubbles-chatgpt-agent
  newTag: 3f1f72dae841458f61d96d74f91e4c279dfabf70-115
