apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bluebubbles-chatgpt-agent
resources:
- be-components.yaml
images:
- name: ghcr.io/omega-bred/bluebubbles-chatgpt-agent
  newName: ghcr.io/omega-bred/bluebubbles-chatgpt-agent
  newTag: 825d1ba78b12598c180d2d854e1897236a5bbc7b-97
