apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bluebubbles-chatgpt-agent
resources:
- be-components.yaml
images:
- name: registry.breland.io/omega-bred/bluebubbles-chatgpt-agent
  newName: registry.breland.io/omega-bred/bluebubbles-chatgpt-agent
  newTag: 19a049cae5589dff26891da1bd8449d0bb2569bc-20
